use_frameworks!

platform :ios, '9.0'

target 'MVVMTableViewDemo_Example' do
  pod 'MVVMTableViewDemo', :path => '../'

  target 'MVVMTableViewDemo_Tests' do
    inherit! :search_paths

    
  end
end
